### ISSUE TITLE
What this framework is about ?

### ISSUE THREAD

**Issue by nurmohammed840** [blackshadowsoftwareltd/Modular-Peer-to-Peer-Networking-Framework#1]

**Comment by blackshadowsoftwareltd** [comment]
This is a practice project using rust. here I used some networking modular frameworks. like peer-to-peer.

**Comment by nurmohammed840** [comment]
Would you like to describe more ? Like:

- Architecture
- Usage (How to use it)
- Features and Goal
- Alternative network framework

**Comment by blackshadowsoftwareltd** [comment]
I haven't maintained any convention. just learning about the libp2p package.
